// <auto-generated />
using System;
using Meevent_API.src.Core.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Meevent_API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251130103603_PrimeraMigracion")]
    partial class PrimeraMigracion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Meevent_API.src.Features.ArtistProfiles.ArtistProfileEntity", b =>
                {
                    b.Property<int>("IdArtistProfile")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdArtistProfile"));

                    b.Property<string>("Biography")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FacebookUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InstagramUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StageName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TiktokUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdArtistProfile");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("ArtistProfiles", (string)null);
                });

            modelBuilder.Entity("Meevent_API.src.Features.OrganizerProfiles.OrganizerProfileEntity", b =>
                {
                    b.Property<int>("IdOrganizerProfile")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdOrganizerProfile"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FacebookUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InstagramUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrganizationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneContact")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TiktokUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TwitterUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdOrganizerProfile");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("OrganizerProfiles", (string)null);
                });

            modelBuilder.Entity("Meevent_API.src.Features.OrganizerReviews.OrganizerReviewEntity", b =>
                {
                    b.Property<int>("IdOrganizerReview")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdOrganizerReview"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsVerifiedBuyer")
                        .HasColumnType("bit");

                    b.Property<int>("OrganizerProfileId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("WasHelpfulCount")
                        .HasColumnType("int");

                    b.HasKey("IdOrganizerReview");

                    b.HasIndex("OrganizerProfileId");

                    b.HasIndex("UserId");

                    b.ToTable("OrganizerReviews", (string)null);
                });

            modelBuilder.Entity("Meevent_API.src.Features.Users.UserEntity", b =>
                {
                    b.Property<int>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUser"));

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVerifiedEmail")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfileImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdUser");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Meevent_API.src.Features.Wishlists.WishlistEntity", b =>
                {
                    b.Property<int>("IdWishlist")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdWishlist"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("IdWishlist");

                    b.HasIndex("UserId");

                    b.ToTable("Wishlists", (string)null);
                });

            modelBuilder.Entity("Meevent_API.src.Features.ArtistProfiles.ArtistProfileEntity", b =>
                {
                    b.HasOne("Meevent_API.src.Features.Users.UserEntity", "User")
                        .WithOne("ArtistProfile")
                        .HasForeignKey("Meevent_API.src.Features.ArtistProfiles.ArtistProfileEntity", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Meevent_API.src.Features.OrganizerProfiles.OrganizerProfileEntity", b =>
                {
                    b.HasOne("Meevent_API.src.Features.Users.UserEntity", "User")
                        .WithOne("OrganizerProfile")
                        .HasForeignKey("Meevent_API.src.Features.OrganizerProfiles.OrganizerProfileEntity", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Meevent_API.src.Features.OrganizerReviews.OrganizerReviewEntity", b =>
                {
                    b.HasOne("Meevent_API.src.Features.OrganizerProfiles.OrganizerProfileEntity", "OrganizerProfile")
                        .WithMany("OrganizerReviews")
                        .HasForeignKey("OrganizerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Meevent_API.src.Features.Users.UserEntity", "User")
                        .WithMany("OrganizerReviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OrganizerProfile");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Meevent_API.src.Features.Wishlists.WishlistEntity", b =>
                {
                    b.HasOne("Meevent_API.src.Features.Users.UserEntity", "User")
                        .WithMany("Wishlists")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Meevent_API.src.Features.OrganizerProfiles.OrganizerProfileEntity", b =>
                {
                    b.Navigation("OrganizerReviews");
                });

            modelBuilder.Entity("Meevent_API.src.Features.Users.UserEntity", b =>
                {
                    b.Navigation("ArtistProfile");

                    b.Navigation("OrganizerProfile");

                    b.Navigation("OrganizerReviews");

                    b.Navigation("Wishlists");
                });
#pragma warning restore 612, 618
        }
    }
}
